// Array of products, each product is an object with different fieldset

var products = [
  {
    name: "Fish",
    vegetarian: false,
    glutenFree: false,
    organic: false,
    price: 10.0,
    quantity: 0,
    image: "https://i5.walmartimages.ca/images/Enlarge/415/401/6000204415401.jpg",
  },
  {
    name: "Sausage",
    vegetarian: false,
    glutenFree: false,
    organic: false,
    price: 15.0,
    quantity: 0,
    image:"https://lovingitvegan.com/wp-content/uploads/2021/03/Vegan-Sausages-24-500x500.jpg",
  },
  {
    name: "Organic beef",
    vegetarian: false,
    glutenFree: false,
    organic: true,
    price: 13.0,
    quantity: 0,
    image:"https://cdn.britannica.com/68/143268-050-917048EA/Beef-loin.jpg",
  },
  {
    name: "Bread",
    vegetarian: true,
    glutenFree: false,
    organic: false,
    price: 4.0,
    quantity: 0,
    image:"https://tastesbetterfromscratch.com/wp-content/uploads/2020/03/Bread-Recipe-5-2.jpg",

  },
  {
    name: "Organic blueberrie",
    vegetarian: true,
    glutenFree: false,
    organic: true,
    price: 3.0,
    quantity: 0,
    image:"https://images-prod.healthline.com/hlcmsresource/images/AN_images/blueberries-1296x728-feature.jpg",

  },
  {
    name: "Organic Bananas",
    vegetarian: true,
    glutenFree: false,
    organic: true,
    price: 2.0,
    quantity: 0,
    image:"https://images.immediate.co.uk/production/volatile/sites/30/2017/01/Bunch-of-bananas-67e91d5.jpg?quality=90&resize=440,400" ,
  },
  {
    name: "Tofu",
    vegetarian: true,
    glutenFree: false,
    organic: false,
    price: 5.0,
    quantity: 0,
    image:"https://sweetsimplevegan.com/wp-content/uploads/2020/09/Easy-Crispy-Baked-Tofu-Recipe-Sweet-Simple-Vegan-6.jpg",
  },
  {
    name: "Tomatoes",
    vegetarian: true,
    glutenFree: false,
    organic: false,
    price: 4.0,
    quantity: 0,
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/1200px-Tomato_je.jpg",
  },
  {
    name: "Gluten free whole grain bagel",
    vegetarian: true,
    glutenFree: true,
    organic: false,
    price: 4.0,
    quantity: 0,
    image:"https://www.sideofsneakers.com/wp-content/uploads/2011/10/IMG_0236-500x333_thumb.jpg",

  },
  {
    name: "Gluten free Muffin",
    vegetarian: true,
    glutenFree: true,
    organic: false,
    price: 5.0,
    quantity: 0,
    image:"https://sugargeekshow.com/wp-content/uploads/2019/10/chocolate-chip-muffins-featured.jpg",
  },
];
